# Generated by Django 5.2.11 on 2026-02-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_remove_purchaseitem_purchase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='purchase',
            new_name='bill',
        ),
    ]
